name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        uses: makocchi-git/actions-k8s-manifests-validate@master
        with:
          token: ${{ secrets.GITHUB_API_TOKEN }}
