name: Pull Request Check

on: [pull_request]

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in dir1 and dir2
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.0
        with:
          files: dir1,dir2
          token: ${{ secrets.GITHUB_TOKEN }}

  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in dir1
        uses: makocchi-git/actions-k8s-manifests-conftest@latest
        with:
          file: dir1
          token: ${{ secrets.GITHUB_TOKEN }}
