name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: validate1
        uses: makocchi-git/actions-k8s-manifests-validate@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: validate2
        uses: makocchi-git/actions-k8s-manifests-validate@master
        with:
          token: ${{ secrets.GITHUB_API_TOKEN }}
          files: dir1,dir2
